### ISSUE TITLE
Error metrics of this implementation

### ISSUE THREAD

**Issue by CSU-NXY** [AlphaPlusTT/mipnerf-pytorch#1]
Hi, Thanks for your implementation of Mip-NeRF. How is the error metrics like PSNR of this implementation?

**Comment by ZYang2077** [comment]
https://github.com/AlphaPlusTT/mipnerf-pytorch/blob/3ae1855e99998ff78a2cfbf68d8c0454542f7d0d/utils/loss.py#L11
Thanks for your attention. This repository is still in the development process.

**Comment by hjxwhy** [comment]
Hi, thanks for your code, can you replicate the result with pytorch code?  I am also developing base your code but i modified it to pytorch-lightning, but the result seems bad. The source code has the [grad_norm](https://github.com/google/mipnerf/blob/84c969e0a623edd183b75693aed72a7e7c22902d/train.py#L111), but I am not familiar with JAX, is it the same clip_grad_norm_ in pytorch? How long do you train your code 1 million steps?

**Comment by ZYang2077** [comment]
I'm sorry I've been busy with other things during this period. I'll let you know when I get the result. Previously, single GPU training 1 million steps took 4~5 days :(
